// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Redbadge.Data.Context;

#nullable disable

namespace Redbadge.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230314231826_Rewinding to Old Migrations")]
    partial class RewindingtoOldMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Redbadge.Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock, Paper, Scissors"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mario Kart 8"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jenga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pool"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Odd Ball, Halo Infinite"
                        });
                });

            modelBuilder.Entity("Redbadge.Data.Entities.IndividualResultsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OccasionId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OccasionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RankId");

                    b.ToTable("IndividualResults");
                });

            modelBuilder.Entity("Redbadge.Data.Entities.OccasionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Occasion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2023, 3, 14, 19, 18, 26, 330, DateTimeKind.Local).AddTicks(7313),
                            Name = "Bryan's Bachelor Party"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2023, 3, 14, 19, 18, 26, 330, DateTimeKind.Local).AddTicks(7352),
                            Name = "That one time at Kyle's house"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2023, 3, 14, 19, 18, 26, 330, DateTimeKind.Local).AddTicks(7355),
                            Name = "August 13th, 1998"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2023, 3, 14, 19, 18, 26, 330, DateTimeKind.Local).AddTicks(7357),
                            Name = "2004 Xmas Party"
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2023, 3, 14, 19, 18, 26, 330, DateTimeKind.Local).AddTicks(7361),
                            Name = "07/04/2021"
                        });
                });

            modelBuilder.Entity("Redbadge.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Michael"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khadir"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bryan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thomas"
                        });
                });

            modelBuilder.Entity("Redbadge.Data.Entities.RankEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rank");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RankName = "Winner"
                        },
                        new
                        {
                            Id = 2,
                            RankName = "Loser"
                        },
                        new
                        {
                            Id = 3,
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 5,
                            RankName = "Bronze"
                        });
                });

            modelBuilder.Entity("Redbadge.Data.Entities.IndividualResultsEntity", b =>
                {
                    b.HasOne("Redbadge.Data.Entities.GameEntity", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Redbadge.Data.Entities.OccasionEntity", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Redbadge.Data.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Redbadge.Data.Entities.RankEntity", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Occasion");

                    b.Navigation("Player");

                    b.Navigation("Rank");
                });
#pragma warning restore 612, 618
        }
    }
}
